const fs = require('fs');
const path = require('path');

const EXTRACTED_DIR = path.join(__dirname, '../assets/extracted_videos');
const MAP_FILE = path.join(__dirname, '../src/utils/videoMap.ts');

if (!fs.existsSync(EXTRACTED_DIR)) {
  console.error('Extracted directory not found:', EXTRACTED_DIR);
  process.exit(1);
}

const files = fs.readdirSync(EXTRACTED_DIR).filter(file => file.endsWith('.mp4'));

let cases = '';
files.forEach(file => {
  const id = file.replace('.mp4', '');
  // Map both case-sensitive and normal formats if needed
  cases += `    case '${id}':\n      return require('../../assets/extracted_videos/${file}');\n`;
  
  // also check if we need to map alphabetical ones with prefix or without prefix
  if (id.startsWith('asl_')) {
    const rawLetter = id.replace('asl_', '');
    cases += `    case '${rawLetter}':\n      return require('../../assets/extracted_videos/${file}');\n`;
  } else {
    // If id is "thankyou", but sign.id is "thank you" or "thank_you"
    // Let's add mapping for common variations
    const spaced = id.replace(/([A-Z])/g, ' $1').trim().toLowerCase();
    if (spaced !== id) {
      cases += `    case '${spaced}':\n      return require('../../assets/extracted_videos/${file}');\n`;
    }
  }
});

const content = `// This file is auto-generated by scripts/generate_videomap.js
// Do not edit manually.

export function getVideoAsset(id: string): any {
  if (!id) return null;
  
  const normalizedId = id.toLowerCase().replace(/\\s+/g, '');
  
  switch (normalizedId) {
${cases}    default:
      return null;
  }
}
`;

fs.writeFileSync(MAP_FILE, content, 'utf-8');
console.log('✅ Generated videoMap.ts successfully with', files.length, 'video assets!');
